Repository simonadamgyula/Proj1-valorant-9C, pull requests merged in 2023-03, with the labels that each got.

#56 about oldal nagyából véglegesítve
  about.html
  style.css
Labels: enhancement, about

#59 about oldalra képek megvannak
  about.html
  sources/about/armoutkep.jpeg
  sources/about/dzsulakep.jpeg
Labels: about, source

#60 57 agent oldal nagyjából véglegesítése
  agents.html
  index.js
  sources/abilities/Credits_icon.png
  sources/abilities/Phoenix_C.png
  sources/abilities/Phoenix_E.png
  sources/abilities/Phoenix_Q.png
  sources/abilities/Phoenix_X.png
  style.css
Labels: enhancement, agents

#61 44 main oldalra valami
  index.html
  style.css
Labels: index

#65 64 agent oldal fejlesztése
  agents.html
  index.js
  style.css
Labels: enhancement, agents, style

#63 done?
  agents.html
  index.html
  index.js
  quiz.js
  style.css
Labels: index, style

#69 index is responsive
  style.css
Labels: bug, index

#71 hahahahaha
  about.html
  idk.html
Labels: bug

#72 hahahha
  index.html
Labels: bug

#74 oldolak validak
  about.html
  agents.html
  index.html
  style.css
Labels: bug

#76 favicon hozzáadva
  about.html
  agents.html
  index.html
  maps.html
  quiz.html
  sources/logo.png
Labels: enhancement

#78 helyesíárasi hibák kijavítva
  index.html
Labels: bug, enhancement

#80 magyarosítás megtörtént
  quiz.html
  quiz.js
Labels: bug

#82 megvan
  about.html
  agents.html
  quiz.js
Labels: bug, invalid
